### ISSUE TITLE
Update to Gradle 5.x

### ISSUE THREAD

**Issue by koolnet5555** [myniva/gradle-s3-build-cache#18]
Are you planning to update this repo with Gradle 5.x ?

**Comment by trevjonez** [comment]
there shouldn't be any thing stopping you from consuming it from a project using the latest gradle version (5.4.1 at the time of writing).

I forked and with a few updates to build.gradle had it running on 5.4.1 for its own build as well. From there the code built and passed its included tests as is. The remote cache api's don't seem to have been changed since gradle 3.5 at least not in a breaking way.

**Comment by myniva** [comment]
As the Remote Cache API is stable, the plugin should be compatible with any Gradle version >= 4. @koolnet5555 if you encounter any issues, please open a new issue with a more detailed error message.
