### ISSUE TITLE
Don't use a dynamic version for com.amazonaws:aws-java-sdk-s3

### ISSUE THREAD

**Issue by erdi** [myniva/gradle-s3-build-cache#20]
Dynamic versions published in the pom cause unnecessary trips to maven repo to check if new version is available for consumers and can lead to non-reproducible builds

**Comment by nhoughto** [comment]
Simplest workaround for this is to use the older style gradle plugin declaration with a resolution strategy
```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.ch.myniva.gradle:s3-build-cache:0.9.0"
    }
    //This is to solve for https://github.com/myniva/gradle-s3-build-cache/issues/20
    configurations.classpath {
        resolutionStrategy {
            force 'com.amazonaws:aws-java-sdk-s3:1.11.582'
        }
    }
}
apply plugin: ch.myniva.gradle.caching.s3.AwsS3Plugin
```

**Comment by bsideup** [comment]
FYI this one have caused us a major CI breakage because new SDK's version is unavailable for some reason.

We did lock the version (as was suggested by @nhoughto, thanks!), but this sounds rather a problem with the plugin, so please, consider fixing it ASAP (especially given the unavailability of the SDK's version that I expect to affect every other project too)

**Comment by mkrup** [comment]
@myniva, Hi!
Thanks for the great plugin.
I have a case when one build fills cache and then other builds read data from it.
When new version of amazon sdk is being published in the middle of the pipeline then it changes all cache keys and depndednt builds take nothing from cache.
Do you have plans to fix the issue?
